// class Autogenerated {
//   int? id;
//   String? uid;
//   String? nameProduct;
//   String? imageProduct;
//   int? amount;
//   int? price;
//   int? sell;
//   int? buy;
//   String? createAt;
//   String? updateAt;
//
//   Autogenerated(
//       {this.id,
//         this.uid,
//         this.nameProduct,
//         this.imageProduct,
//         this.amount,
//         this.price,
//         this.sell,
//         this.buy,
//         this.createAt,
//         this.updateAt});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     uid = json['uid'];
//     nameProduct = json['name_product'];
//     imageProduct = json['image_product'];
//     amount = json['amount'];
//     price = json['price'];
//     sell = json['sell'];
//     buy = json['buy'];
//     createAt = json['create_At'];
//     updateAt = json['update_At'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['uid'] = this.uid;
//     data['name_product'] = this.nameProduct;
//     data['image_product'] = this.imageProduct;
//     data['amount'] = this.amount;
//     data['price'] = this.price;
//     data['sell'] = this.sell;
//     data['buy'] = this.buy;
//     data['create_At'] = this.createAt;
//     data['update_At'] = this.updateAt;
//     return data;
//   }
// }